-- HOOTOOM Forum MVP 初始化数据库结构（精简版）
-- MySQL 8.0+；应用统一按 UTC 写入 DATETIME(3)。

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE forum_user (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '前台用户ID',
    username VARCHAR(32) NOT NULL COMMENT '登录用户名，规范化为小写',
    email VARCHAR(254) NOT NULL COMMENT '登录邮箱，规范化保存',
    email_verified_at DATETIME(3) NULL COMMENT '邮箱验证时间',
    password_hash VARCHAR(100) NOT NULL COMMENT 'BCrypt密码哈希',
    token_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '令牌版本，改密或禁用时递增',
    nickname VARCHAR(40) NOT NULL COMMENT '显示昵称，可重复',
    avatar_key VARCHAR(64) NOT NULL DEFAULT 'default-1' COMMENT '系统内置头像标识',
    bio VARCHAR(500) NULL COMMENT '个人简介',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING待验证、ACTIVE正常、DISABLED禁用',
    policy_version VARCHAR(32) NOT NULL COMMENT '已同意的协议版本',
    policy_accepted_at DATETIME(3) NOT NULL COMMENT '协议同意时间',
    approved_post_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '累计通过审核帖子数',
    last_login_at DATETIME(3) NULL COMMENT '最后成功登录时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_forum_user_username (username),
    UNIQUE KEY uk_forum_user_email (email),
    KEY idx_forum_user_status_created (status, created_at, id),
    CONSTRAINT ck_forum_user_status CHECK (status IN ('PENDING', 'ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='前台论坛用户表';

CREATE TABLE admin_user (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '后台账号ID',
    role_code VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '固定角色编码：OPERATOR运营、ADMIN管理员',
    username VARCHAR(32) NOT NULL COMMENT '后台登录用户名，规范化为小写',
    email VARCHAR(254) NOT NULL COMMENT '后台账号邮箱',
    password_hash VARCHAR(100) NOT NULL COMMENT 'BCrypt密码哈希',
    token_version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '令牌版本，改密或禁用时递增',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE正常、DISABLED禁用',
    last_login_at DATETIME(3) NULL COMMENT '最后成功登录时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_user_username (username),
    UNIQUE KEY uk_admin_user_email (email),
    KEY idx_admin_user_role_status (role_code, status, id),
    KEY idx_admin_user_status_created (status, created_at, id),
    CONSTRAINT ck_admin_user_role CHECK (role_code IN ('OPERATOR', 'ADMIN')),
    CONSTRAINT ck_admin_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='后台管理账号表';

CREATE TABLE refresh_token (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '刷新令牌记录ID',
    subject_type VARCHAR(16) NOT NULL COMMENT '主体类型：USER前台用户、ADMIN后台账号',
    user_id BIGINT UNSIGNED NULL COMMENT '前台用户ID',
    admin_user_id BIGINT UNSIGNED NULL COMMENT '后台账号ID',
    token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '刷新令牌SHA-256哈希',
    family_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '令牌轮换族UUID',
    device_name VARCHAR(100) NULL COMMENT '设备名称或客户端摘要',
    expires_at DATETIME(3) NOT NULL COMMENT '过期时间',
    last_used_at DATETIME(3) NULL COMMENT '最后使用时间',
    revoked_at DATETIME(3) NULL COMMENT '撤销时间',
    revoke_reason VARCHAR(64) NULL COMMENT '撤销原因编码',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_refresh_token_hash (token_hash),
    KEY idx_refresh_token_user (user_id, revoked_at, expires_at),
    KEY idx_refresh_token_admin (admin_user_id, revoked_at, expires_at),
    KEY idx_refresh_token_family (family_id, created_at),
    KEY idx_refresh_token_expiry (expires_at, id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_refresh_token_admin FOREIGN KEY (admin_user_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_refresh_token_subject CHECK ((subject_type = 'USER' AND user_id IS NOT NULL AND admin_user_id IS NULL) OR (subject_type = 'ADMIN' AND user_id IS NULL AND admin_user_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='刷新令牌和设备会话表';

CREATE TABLE email_token (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮件一次性令牌ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '前台用户ID',
    purpose VARCHAR(32) NOT NULL COMMENT '用途：VERIFY_EMAIL验证邮箱、RESET_PASSWORD重置密码',
    token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '一次性令牌SHA-256哈希',
    attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '验证失败次数',
    expires_at DATETIME(3) NOT NULL COMMENT '过期时间',
    used_at DATETIME(3) NULL COMMENT '使用时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_email_token_hash (token_hash),
    KEY idx_email_token_user_purpose (user_id, purpose, used_at, expires_at),
    KEY idx_email_token_expiry (expires_at, id),
    CONSTRAINT fk_email_token_user FOREIGN KEY (user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_email_token_purpose CHECK (purpose IN ('VERIFY_EMAIL', 'RESET_PASSWORD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邮箱验证和密码重置令牌表';

CREATE TABLE category (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '板块ID',
    name VARCHAR(80) NOT NULL COMMENT '板块名称',
    slug VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '板块URL唯一标识',
    description VARCHAR(500) NULL COMMENT '板块简介',
    icon_key VARCHAR(64) NULL COMMENT '板块图标标识',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
    is_recommended TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否推荐：0否、1是',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE启用、DISABLED禁用、ARCHIVED归档',
    post_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '公开帖子数量快照',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_category_slug (slug),
    KEY idx_category_status_sort (status, sort_order, id),
    KEY idx_category_recommended_sort (is_recommended, status, sort_order, id),
    CONSTRAINT ck_category_status CHECK (status IN ('ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT ck_category_recommended CHECK (is_recommended IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论坛板块表';

CREATE TABLE forum_post (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '帖子ID',
    category_id BIGINT UNSIGNED NOT NULL COMMENT '当前公开版本所属板块ID',
    author_user_id BIGINT UNSIGNED NOT NULL COMMENT '前台作者用户ID',
    client_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端防重复提交标识',
    published_revision_id BIGINT UNSIGNED NULL COMMENT '当前已发布版本ID',
    pending_revision_id BIGINT UNSIGNED NULL COMMENT '当前待审或驳回版本ID',
    created_by_admin_id BIGINT UNSIGNED NULL COMMENT '代表官方发帖的后台账号ID',
    business_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '状态：NORMAL正常、LOCKED锁定、DELETED删除',
    is_official TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否官方内容：0否、1是',
    is_featured TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否精华：0否、1是',
    pin_scope VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT '置顶范围：NONE、CATEGORY、GLOBAL',
    pinned_at DATETIME(3) NULL COMMENT '置顶时间',
    view_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '累计有效浏览数快照',
    like_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数快照',
    favorite_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '收藏数快照',
    comment_count BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '公开评论数快照',
    next_floor_no INT UNSIGNED NOT NULL DEFAULT 1 COMMENT '下一个评论楼层号',
    last_activity_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '最后公开活动时间',
    published_at DATETIME(3) NULL COMMENT '首次公开发布时间',
    delete_reason VARCHAR(500) NULL COMMENT '删除原因',
    deleted_by_type VARCHAR(16) NULL COMMENT '删除者类型：USER、ADMIN',
    deleted_by_id BIGINT UNSIGNED NULL COMMENT '删除者ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted_at DATETIME(3) NULL COMMENT '软删除时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_forum_post_user_request (author_user_id, client_request_id),
    KEY idx_forum_post_category_list (category_id, business_status, pin_scope, last_activity_at DESC, id DESC),
    KEY idx_forum_post_latest (business_status, last_activity_at DESC, id DESC),
    KEY idx_forum_post_official (business_status, is_official, published_at DESC, id DESC),
    KEY idx_forum_post_featured (business_status, is_featured, last_activity_at DESC, id DESC),
    KEY idx_forum_post_author (author_user_id, created_at DESC, id DESC),
    KEY idx_forum_post_published_revision (published_revision_id, id),
    KEY idx_forum_post_pending_revision (pending_revision_id, id),
    CONSTRAINT fk_forum_post_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_forum_post_author FOREIGN KEY (author_user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_forum_post_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_forum_post_status CHECK (business_status IN ('NORMAL', 'LOCKED', 'DELETED')),
    CONSTRAINT ck_forum_post_pin_scope CHECK (pin_scope IN ('NONE', 'CATEGORY', 'GLOBAL')),
    CONSTRAINT ck_forum_post_revision_pointers CHECK (published_revision_id IS NULL OR pending_revision_id IS NULL OR published_revision_id <> pending_revision_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论坛帖子主表';

CREATE TABLE post_revision (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '帖子版本ID',
    post_id BIGINT UNSIGNED NOT NULL COMMENT '所属帖子ID',
    revision_no INT UNSIGNED NOT NULL COMMENT '帖子内版本号，从1递增',
    title VARCHAR(120) NOT NULL COMMENT '版本标题',
    category_id BIGINT UNSIGNED NOT NULL COMMENT '版本目标板块ID',
    markdown_content MEDIUMTEXT NOT NULL COMMENT 'Markdown原文',
    rendered_html MEDIUMTEXT NOT NULL COMMENT '服务端净化后的HTML',
    review_status VARCHAR(16) NOT NULL COMMENT '审核状态：PENDING、APPROVED、REJECTED',
    review_method VARCHAR(16) NULL COMMENT '审核方式：AUTO自动、MANUAL人工',
    reject_reason VARCHAR(500) NULL COMMENT '驳回原因',
    created_by_type VARCHAR(16) NOT NULL COMMENT '创建者类型：USER、ADMIN',
    created_by_user_id BIGINT UNSIGNED NULL COMMENT '创建版本的前台用户ID',
    created_by_admin_id BIGINT UNSIGNED NULL COMMENT '创建版本的后台账号ID',
    reviewed_by_admin_id BIGINT UNSIGNED NULL COMMENT '人工审核后台账号ID',
    reviewed_at DATETIME(3) NULL COMMENT '审核时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_post_revision_no (post_id, revision_no),
    UNIQUE KEY uk_post_revision_id_post (id, post_id),
    KEY idx_post_revision_review_queue (review_status, created_at, id),
    KEY idx_post_revision_category_review (category_id, review_status, created_at, id),
    KEY idx_post_revision_creator_user (created_by_user_id, created_at),
    KEY idx_post_revision_creator_admin (created_by_admin_id, created_at),
    FULLTEXT KEY ft_post_revision_content (title, markdown_content) WITH PARSER ngram,
    CONSTRAINT fk_post_revision_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_revision_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_revision_user FOREIGN KEY (created_by_user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_revision_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_revision_reviewer FOREIGN KEY (reviewed_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_post_revision_status CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_post_revision_method CHECK (review_method IN ('AUTO', 'MANUAL') OR review_method IS NULL),
    CONSTRAINT ck_post_revision_creator CHECK ((created_by_type = 'USER' AND created_by_user_id IS NOT NULL AND created_by_admin_id IS NULL) OR (created_by_type = 'ADMIN' AND created_by_user_id IS NULL AND created_by_admin_id IS NOT NULL)),
    CONSTRAINT ck_post_revision_review_result CHECK ((review_status = 'PENDING' AND review_method IS NULL AND reviewed_by_admin_id IS NULL AND reviewed_at IS NULL AND reject_reason IS NULL) OR (review_status = 'APPROVED' AND review_method IN ('AUTO', 'MANUAL') AND reviewed_at IS NOT NULL AND reject_reason IS NULL AND ((review_method = 'AUTO' AND reviewed_by_admin_id IS NULL) OR (review_method = 'MANUAL' AND reviewed_by_admin_id IS NOT NULL))) OR (review_status = 'REJECTED' AND review_method IN ('AUTO', 'MANUAL') AND reviewed_at IS NOT NULL AND reject_reason IS NOT NULL AND ((review_method = 'AUTO' AND reviewed_by_admin_id IS NULL) OR (review_method = 'MANUAL' AND reviewed_by_admin_id IS NOT NULL))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='帖子版本和审核表';

ALTER TABLE forum_post
    ADD CONSTRAINT fk_forum_post_published_revision FOREIGN KEY (published_revision_id, id) REFERENCES post_revision (id, post_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    ADD CONSTRAINT fk_forum_post_pending_revision FOREIGN KEY (pending_revision_id, id) REFERENCES post_revision (id, post_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE forum_comment (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
    post_id BIGINT UNSIGNED NOT NULL COMMENT '所属帖子ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '评论作者用户ID',
    client_request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '客户端防重复提交标识',
    reply_to_comment_id BIGINT UNSIGNED NULL COMMENT '被回复评论ID',
    floor_no INT UNSIGNED NOT NULL COMMENT '帖子内固定楼层号',
    markdown_content TEXT NOT NULL COMMENT '评论Markdown原文',
    rendered_html MEDIUMTEXT NOT NULL COMMENT '服务端净化后的HTML',
    review_status VARCHAR(16) NOT NULL COMMENT '审核状态：PENDING、APPROVED、REJECTED',
    review_method VARCHAR(16) NULL COMMENT '审核方式：AUTO自动、MANUAL人工',
    business_status VARCHAR(16) NOT NULL DEFAULT 'NORMAL' COMMENT '业务状态：NORMAL正常、DELETED删除',
    reject_reason VARCHAR(500) NULL COMMENT '驳回原因',
    reviewed_by_admin_id BIGINT UNSIGNED NULL COMMENT '人工审核后台账号ID',
    reviewed_at DATETIME(3) NULL COMMENT '审核时间',
    delete_reason VARCHAR(500) NULL COMMENT '删除原因',
    deleted_by_type VARCHAR(16) NULL COMMENT '删除者类型：USER、ADMIN',
    deleted_by_id BIGINT UNSIGNED NULL COMMENT '删除者ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    deleted_at DATETIME(3) NULL COMMENT '软删除时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_forum_comment_user_request (user_id, client_request_id),
    UNIQUE KEY uk_forum_comment_floor (post_id, floor_no),
    UNIQUE KEY uk_forum_comment_id_post (id, post_id),
    KEY idx_forum_comment_post_list (post_id, review_status, business_status, floor_no),
    KEY idx_forum_comment_user (user_id, created_at DESC, id DESC),
    KEY idx_forum_comment_reply (reply_to_comment_id, post_id),
    KEY idx_forum_comment_review_queue (review_status, created_at, id),
    CONSTRAINT fk_forum_comment_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_forum_comment_user FOREIGN KEY (user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_forum_comment_reply FOREIGN KEY (reply_to_comment_id, post_id) REFERENCES forum_comment (id, post_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_forum_comment_reviewer FOREIGN KEY (reviewed_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_forum_comment_review CHECK (review_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_forum_comment_method CHECK (review_method IN ('AUTO', 'MANUAL') OR review_method IS NULL),
    CONSTRAINT ck_forum_comment_status CHECK (business_status IN ('NORMAL', 'DELETED')),
    CONSTRAINT ck_forum_comment_review_result CHECK ((review_status = 'PENDING' AND review_method IS NULL AND reviewed_by_admin_id IS NULL AND reviewed_at IS NULL AND reject_reason IS NULL) OR (review_status = 'APPROVED' AND review_method IN ('AUTO', 'MANUAL') AND reviewed_at IS NOT NULL AND reject_reason IS NULL AND ((review_method = 'AUTO' AND reviewed_by_admin_id IS NULL) OR (review_method = 'MANUAL' AND reviewed_by_admin_id IS NOT NULL))) OR (review_status = 'REJECTED' AND review_method IN ('AUTO', 'MANUAL') AND reviewed_at IS NOT NULL AND reject_reason IS NOT NULL AND ((review_method = 'AUTO' AND reviewed_by_admin_id IS NULL) OR (review_method = 'MANUAL' AND reviewed_by_admin_id IS NOT NULL))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论坛评论表';

CREATE TABLE post_like (
    user_id BIGINT UNSIGNED NOT NULL COMMENT '点赞用户ID',
    post_id BIGINT UNSIGNED NOT NULL COMMENT '帖子ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '点赞时间',
    PRIMARY KEY (user_id, post_id),
    KEY idx_post_like_post_created (post_id, created_at, user_id),
    CONSTRAINT fk_post_like_user FOREIGN KEY (user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_like_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='帖子点赞表';

CREATE TABLE post_favorite (
    user_id BIGINT UNSIGNED NOT NULL COMMENT '收藏用户ID',
    post_id BIGINT UNSIGNED NOT NULL COMMENT '帖子ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '收藏时间',
    PRIMARY KEY (user_id, post_id),
    KEY idx_post_favorite_post (post_id, created_at, user_id),
    KEY idx_post_favorite_user_time (user_id, created_at DESC, post_id),
    CONSTRAINT fk_post_favorite_user FOREIGN KEY (user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_post_favorite_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='帖子收藏表';

CREATE TABLE report (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '举报ID',
    reporter_user_id BIGINT UNSIGNED NOT NULL COMMENT '举报用户ID',
    target_type VARCHAR(16) NOT NULL COMMENT '目标类型：POST、COMMENT',
    target_id BIGINT UNSIGNED NOT NULL COMMENT '举报目标ID',
    reason_type VARCHAR(32) NOT NULL COMMENT '举报原因类型',
    description VARCHAR(1000) NULL COMMENT '补充说明',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、RESOLVED、REJECTED',
    handled_by_admin_id BIGINT UNSIGNED NULL COMMENT '处理后台账号ID',
    handle_note VARCHAR(1000) NULL COMMENT '处理备注',
    handled_at DATETIME(3) NULL COMMENT '处理时间',
    active_key VARCHAR(200) CHARACTER SET ascii COLLATE ascii_bin GENERATED ALWAYS AS (CASE WHEN status = 'PENDING' THEN CONCAT(reporter_user_id, ':', target_type, ':', target_id) ELSE NULL END) STORED COMMENT '待处理举报唯一键',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_report_active_key (active_key),
    KEY idx_report_queue (status, created_at, id),
    KEY idx_report_target (target_type, target_id, status),
    KEY idx_report_user (reporter_user_id, created_at DESC, id DESC),
    CONSTRAINT fk_report_user FOREIGN KEY (reporter_user_id) REFERENCES forum_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_report_admin FOREIGN KEY (handled_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_report_target CHECK (target_type IN ('POST', 'COMMENT')),
    CONSTRAINT ck_report_status CHECK (status IN ('PENDING', 'RESOLVED', 'REJECTED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='内容举报表';

CREATE TABLE sensitive_word (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '敏感词ID',
    word VARCHAR(200) NOT NULL COMMENT '敏感词原始文本',
    normalized_word VARCHAR(200) NOT NULL COMMENT '规范化匹配文本',
    match_type VARCHAR(16) NOT NULL DEFAULT 'CONTAINS' COMMENT '匹配方式：EXACT、CONTAINS',
    action VARCHAR(16) NOT NULL DEFAULT 'REVIEW' COMMENT '命中动作：REVIEW转审核、REJECT拒绝',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态：ACTIVE、DISABLED',
    created_by_admin_id BIGINT UNSIGNED NOT NULL COMMENT '创建后台账号ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (id),
    UNIQUE KEY uk_sensitive_word_value (normalized_word, match_type),
    KEY idx_sensitive_word_status (status, action, id),
    CONSTRAINT fk_sensitive_word_admin FOREIGN KEY (created_by_admin_id) REFERENCES admin_user (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_sensitive_word_match CHECK (match_type IN ('EXACT', 'CONTAINS')),
    CONSTRAINT ck_sensitive_word_action CHECK (action IN ('REVIEW', 'REJECT')),
    CONSTRAINT ck_sensitive_word_status CHECK (status IN ('ACTIVE', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='内容敏感词表';

CREATE TABLE audit_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '审计日志ID',
    actor_type VARCHAR(16) NOT NULL COMMENT '操作者类型：USER、ADMIN、SYSTEM',
    actor_id BIGINT UNSIGNED NULL COMMENT '操作者ID，系统任务可为空',
    action VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '操作动作编码',
    target_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '目标资源类型',
    target_id BIGINT UNSIGNED NULL COMMENT '目标资源ID',
    reason VARCHAR(1000) NULL COMMENT '操作原因或备注',
    before_json JSON NULL COMMENT '操作前脱敏快照',
    after_json JSON NULL COMMENT '操作后脱敏快照',
    ip_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '来源IP加盐哈希',
    request_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '请求链路ID',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '操作时间',
    PRIMARY KEY (id),
    KEY idx_audit_actor (actor_type, actor_id, created_at DESC, id DESC),
    KEY idx_audit_target (target_type, target_id, created_at DESC, id DESC),
    KEY idx_audit_action (action, created_at DESC, id DESC),
    KEY idx_audit_request (request_id),
    KEY idx_audit_created (created_at, id),
    CONSTRAINT ck_audit_actor CHECK (actor_type IN ('USER', 'ADMIN', 'SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='管理与安全审计日志表';

CREATE TABLE mail_outbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邮件任务ID',
    template_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '邮件模板编码',
    recipient_ciphertext VARBINARY(512) NOT NULL COMMENT '加密后的收件邮箱',
    payload_ciphertext MEDIUMBLOB NOT NULL COMMENT '加密后的邮件模板参数和一次性链接数据',
    encryption_key_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '数据加密密钥版本',
    business_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '业务幂等键',
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、SENDING、SENT、RETRY、DEAD',
    retry_count SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '重试次数',
    next_retry_at DATETIME(3) NOT NULL COMMENT '下次尝试时间',
    sent_at DATETIME(3) NULL COMMENT '发送成功时间',
    last_error_code VARCHAR(64) NULL COMMENT '最近失败原因编码',
    locked_by VARCHAR(64) NULL COMMENT '处理实例标识',
    locked_at DATETIME(3) NULL COMMENT '任务加锁时间',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_mail_outbox_business (business_key),
    KEY idx_mail_outbox_dispatch (status, next_retry_at, id),
    KEY idx_mail_outbox_lock (locked_at, id),
    CONSTRAINT ck_mail_outbox_status CHECK (status IN ('PENDING', 'SENDING', 'SENT', 'RETRY', 'DEAD'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='可靠邮件投递任务表';

CREATE TABLE post_daily_stat (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '帖子每日统计ID',
    post_id BIGINT UNSIGNED NOT NULL COMMENT '帖子ID',
    stat_date DATE NOT NULL COMMENT 'Asia/Shanghai时区统计日期',
    view_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日有效浏览事件数',
    like_add_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日新增点赞事件数',
    comment_publish_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当日新增公开评论事件数',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_post_daily_stat_date (post_id, stat_date),
    KEY idx_post_daily_stat_hot (stat_date, post_id),
    CONSTRAINT fk_post_daily_stat_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='帖子每日热门度统计表';
